//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Node.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Node.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap anchor_off {
            get {
                object obj = ResourceManager.GetObject("anchor_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap anchor_on {
            get {
                object obj = ResourceManager.GetObject("anchor_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Saving.
        /// </summary>
        internal static string OptionsFailedSaving {
            get {
                return ResourceManager.GetString("OptionsFailedSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save changes to settings. Continue?.
        /// </summary>
        internal static string OptionsFailedSavingMessage {
            get {
                return ResourceManager.GetString("OptionsFailedSavingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon scheduled_tasks {
            get {
                object obj = ResourceManager.GetObject("scheduled_tasks", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scheduled_tasks_icon_48x48 {
            get {
                object obj = ResourceManager.GetObject("scheduled_tasks_icon_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is recommend to exit via the Shutdown command.
        ///Are you sure you want to force an exit?.
        /// </summary>
        internal static string Shutdown_Message {
            get {
                return ResourceManager.GetString("Shutdown_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Exit?.
        /// </summary>
        internal static string Shutdown_Title {
            get {
                return ResourceManager.GetString("Shutdown_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to stop &quot;{0}&quot;?.
        /// </summary>
        internal static string STOP_JOB_MESSAGE {
            get {
                return ResourceManager.GetString("STOP_JOB_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Job?.
        /// </summary>
        internal static string STOP_JOB_TITLE {
            get {
                return ResourceManager.GetString("STOP_JOB_TITLE", resourceCulture);
            }
        }
    }
}
