using System.Collections.Generic;
using System.Linq;
using DataSources;

namespace DataSourceEntity.Templates
{
    /// <summary>
    /// This class generated by DataSourceEntity tool.
    /// TO NOT EDIT
    /// </summary>
    // ReSharper disable InconsistentNaming
    // ReSharper disable NotAccessedField.Global
    // ReSharper disable MemberCanBePrivate.Global
    public partial class SampleEntity : RecordEntity
    {
        /// <summary>
        /// Creates a list of {{ClassName}} objects from a collection of Record objects.
        /// </summary>
        public static List<SampleEntity> ToList(IEnumerable<Record> pRecords)
        {
            return (from record in pRecords select new SampleEntity(record)).ToList();
        }

        public string Title
        {
            get { return _Record.getString("title"); }
            set { _Record["title"] = value; }
        }

        /// <summary>
        /// Constructor
        /// </summary>
        public SampleEntity()
            : base(new Record())
        {
        }

        /// <summary>
        /// Constructor
        /// </summary>
        public SampleEntity(Record pRecord)
            : base(pRecord)
        {
        }
    }
}